kind: pipeline
type: docker
name: test

steps:
  - name: build
    image: node
    commands:
      - npm install
      - npm build

  - name: test
    image: node
    commands:
      - npm test

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
      files:
        - ./coverage/lcov.info

---
kind: pipeline
type: docker
name: publish

steps:
  - name: build
    image: node
    commands:
      - npm install
      - npm build

  - name: npm
    image: plugins/npm
    settings:
      token:
        from_secret: NPM_TOKEN

trigger:
  event:
    - tag
