kind: pipeline
type: docker
name: default

steps:
  - name: jest
    image: node
    commands:
      - npm install
      - npm test

  - name: codecov
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
      files:
        - ./coverage/lcov.info
