kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm test

  - name: coverage
    image: lizheming/drone-coveralls
    settings:
      token:
        from_secret: COVERALLS_REPO_TOKEN
      files:
        - ./coverage/lcov.info
