version: 2.1
orbs:
    node: circleci/node@1.1.6
    codecov: codecov/codecov@1.1.0
jobs:
    build:
        executor: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm test
            - codecov/upload:
                  file: './coverage/'
workflows:
    build:
        jobs:
            - build
