version: 2.1
orbs:
    node: circleci/node@1.1.6
    codecov: codecov/codecov@1.0.2
jobs:
    build:
        executor: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
    test:
        executor: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm test
workflows:
    build_and_test:
        jobs:
            - build
            - test:
                  requires:
                      - build
