version: 2.1
orbs:
    coveralls: coveralls/coveralls@1.0.5
    node: circleci/node@1.1.6
jobs:
    build:
        executor: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm test
            - coveralls/upload:
                  path_to_lcov: ./coverage/lcov.info
workflows:
    build:
        jobs:
            - build
